PROMPT='%F{green}%n@%m%f -> %F{blue}[%3~]%f $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY=" 🙈 "
ZSH_THEME_GIT_PROMPT_CLEAN=" 👌 "
ZSH_THEME_GIT_PROMPT_UNTRACKED=" 🔎 "
ZSH_THEME_GIT_PROMPT_ADDED=""
