export ZSH="/home/joey/.oh-my-zsh"

ZSH_THEME="joeys_custom"

CASE_SENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

ENABLE_CORRECTION="true"

plugins=(git)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting extract)

source $ZSH/oh-my-zsh.sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/joey/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/joey/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/joey/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/joey/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# schedule shutdown with no terminal output
shutdown --poweroff 1:00 &> /dev/null

# Initializes NVM

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Start neofetch to show system info
neofetch
