#!/usr/bin/env bash

function pause() {
   read -p "$* [ENTER TO CONTINUE]"
}

pause "Ready to install some tools, libraries, ... for a development machine ?"

# Just add the commands below to start installing tools, dependencies, ...
sudo apt update
sudo apt install git -y
sudo apt install curl -y
sudo apt install wget -y
sudo apt install screen -y
sudo apt install build-essential -y

# installing zsh
echo "installing zsh"
sudo apt install zsh -y
chsh -s /bin/zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | zsh
rm -rf install.sh

nvm install 18.12.1

# installing zsh plugins
echo "installing zsh plugins"
mkdir ~/.oh-my-zsh/custom/plugins
cd ~/.oh-my-zsh/custom/plugins
git clone git@github.com:zsh-users/zsh-autosuggestions.git
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git

# Installing gcc-arm compiler
cd ~
wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
mv gcc-arm-none-eabi-10.3-2021.10 gnu-arm-embedded
rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
sudo mv gnu-arm-embedded /usr/share/

cd /usr/bin/

# Creating sys links for arm toolchain
sudo ln -s /usr/share/gnu-arm-embedded/bin/arm-none-eabi-cpp
sudo ln -s /usr/share/gnu-arm-embedded/bin/arm-none-eabi-g++
sudo ln -s /usr/share/gnu-arm-embedded/bin/arm-none-eabi-gcc
sudo ln -s /usr/share/gnu-arm-embedded/bin/arm-none-eabi-objcopy

# installing conda
echo "installing conda"
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda3
rm ~/miniconda.sh

# Creating conda env & installing mbed cli
echo "creating mbed env"
conda create -n mbed python=3.7.9
conda activate mbed
pip install mbed-cli

# Installing Nerd Fort
cd ~
mkdir .fonts
cd .fonts
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/SpaceMono/Regular/complete/Space%20Mono%20Nerd%20Font%20Complete.ttf

# Installing zsh powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# The end
pause "All done - best to reboot after rest is done"
